"""Given a string s, partition the string into one or more substrings such that the characters in each
substring are unique. That is, no letter appears in a single substring more than once.

Return the minimum number of substrings in such a partition.

Note that each character should belong to exactly one substring in a partition.

Example 1:

Input: s = "abacaba"
Output: 4
Explanation:
Two possible partitions are ("a","ba","cab","a") and ("ab","a","ca","ba").
It can be shown that 4 is the minimum number of substrings needed.

Example 2:

Input: s = "ssssss"
Output: 6
Explanation:
The only valid partition is ("s","s","s","s","s","s").


Constraints:

1 <= s.length <= 105
s consists of only English lowercase letters.
"""
from collections import Counter


class Solution:
    def partitionString1(self, s: str) -> int:
        # Method 1 : This method is using dictionary and string slicing

        # index -> to iterate through string until next index of same character is found
        # start -> to update current partition start index
        index, start = 0, 0

        # partition -> empty list to store partition of list
        partition = []

        # dictionary to know whether character is already in it: True-> add to partition, update start index,
        # clear dictionary for next partition || False -> continue until already exist character is found
        occurrence = {}

        while index < len(s):

            if s[index] in occurrence:
                partition.append(s[start:index])
                start = index
                occurrence.clear()

            occurrence[s[index]] = 1
            index += 1

        # add one to include last partition
        return len(partition) + 1

    def partitionString2(self, s: str) -> int:
        # Method 2: Using array to store and check if character is occurred again or not
        # Create empty list of len(s) to have partition
        string_list = [0] * len(s)

        # start -> to update with current partition start index
        # partition -> empty list to have unique occurrence of characters
        start = 0
        partition = []

        # iterate through string to find partition
        for index, char in enumerate(s):
            # if character is already in string_list then update partition with the string characters and reset it
            # update start index with current index
            if char in string_list:
                partition.append(s[start:index])
                start = index
                string_list = [0] * len(s)

            # add char to string list if not present
            string_list[index] = char

        return len(partition) + 1

    def partitionString(self, s: str) -> int:
        # Method 3: Using BITS
        index, count, flag = 0, 1, 0
        while index < len(s):
            val = ord(s[index]) - ord('a')
            if flag & (1 << val):
                flag = 0
                count += 1
            flag |= 1 << val
            index += 1
        return count


solution = Solution()
assert 2759 == solution.partitionString(s=
                               "auvplgdhjoddzkknbqlpdtnhevgezqgdwozzvuaalqpfczkacyfjpnatsfyktzcafkrrnkcczwcbjfmxypouqtvsyygbmtcixjrzsatbxffjibxunicghjpjqgdpxsrxxnjpzaeovubnafjufeflfzwnwepkisejnvidapappasyxzmanivmxceeumdyzvjivzvpeqkwiwuqpyjaaosjupckrujmdjqfenirynljhhijitthzgfvjlkcvljwgnkvgrnivvfdhxnhfqblowawuxsvintnatzlzcyohndqxayuirewjjvjgpizglvldessvazussxafzkfknhaczdakmkjrdqxxgjpkqlffzqyxnmennqxjmewzyugxkxukgpitrcyfbvwezozwfiiekmkfryfompyfaajjlvillboexvozpdsftoqcqetbbwpflmekexmznqrnjwuugbtwakzwsgvexwzqalepmxfqfztdceotatfvnxmpvwalwlssguaigvrkdwgezynwwcukrejifcckguroyghrmhzmojcbeuxemubplglsuhlefjbdlexjdjnhbbmlcrspnwliniobcqblubafrcbvbzuuzxrpnatgchrycixlbnqhhtzpxqpcktukqowiehybiakrsgjvdzfplrmzepmutsxqmosgsfdvqleivrccrmvixgbijhfsafuvdhezuznjbavmadylniowlopsyxaltjfnjbucyfylnnmbtqydkqxwdjvadhrlubrdbdrwlbnessjupkqwgtwznjkkdksqabskyofovplwghvirywggkszfgvxwhxxwjgjdzrvumbtszxtsyxeqgrqlmhdzediratwnsbysjramtketuucdirhvrmkeicmggypycptvqjrrvwtabtryfukkdwtzogwgnurvfwbguvdvtsieseioiwlvqxaveyjmvlbqpfprzquoaiptdlhsvqclwimhwcynypckgmokbiowyjzxjmigiirmmvbctwbthtioveqxsehjvcjkdsoxthynysvobiwswwslprptztyhqfnykuohciwcjikvncnzvfhsfgzwaazrodvvgovzrgzxddiophrtortxdmwqdvzzyxsituupdmllgbbpjbrtlmfigsmnhdseqgrzshxntgihtptszutktbuzzmhcavybtqmcawibudggbornqkdpgtpkbbfblajrcoymvnjybkdeuldbfkawkzoyovwwmqatfzpjetbvdglyfmanwccballqcxgdrnblqpsnsfqtojzdzwhejafjudfoogxfxpgtcuepsturarpzitjwumxegvtvamfvcnqkhcgtgtgwxjcsmqybmzsbfxbsuxydjygjkexhxzpwxhefrejlotuasndsmtlnkvqyoghgrzvzwidhvzocuhwvbdgzzjkuwuzdxozswnycmcmohbetucavqgfbwzjihizlumypkwpgswvwffszeytwgkshoexgzuiasuljvikgedwqozgudsalwqxenywozgfuuinwmmorfpgciymuorbjjhbsqitanzoetxlxsxzseytwxhlgaucoftnbnkzfjgynebrvazgyxaxlnrnoscwhdoydxcmwuounoxcfzipmchavpkhtrzptfljzboflfgclnindfuypnxwfogdrqvvhggagngnhexqjzvruszqzknfumevhjyxldpbwuhixxxowlgkkqbnyfpsfwoicgkpotexsyzjqpognqpfqpwgkngcqtnkyzcuaiyqxjmddivwhtmtppcmcbgeunjwxczwlrrpeynocreguiwsmejogsbxcuoiaclafkxaechpzdbokzrgjtipeebpbmxmzngutjxsynfnmkfkipxzbedgapsaimnakjjwlbsiszpprjfbntutxbqksqzmlgafdokfbquncwlygrfmzmwuktopfairmwyscxdfowgbyhjaxnijkblxgjsglasaaovbcrnhkfdnsbzlngqvxtsbrmrwyjgziuprzzajblkewhilbweyfqtcsveqefhrhffpmouolybjkjeheohmozuhqjkzfmsiscgkbonkpoqwejzhlrvqzqfdhfgyuaxsujhvcksyzausikueewvvhsbtnwkmueaondorqecnhcfxzdnnwoozhxkuqjkhpfswddyfexzzuketapvilgecmajbszxllrgwzkbfvtmxfyattvstctapeqxljhayfcwopczydgxhtbxuiuyykxwlvgcevqramjjznuxvwpjdxszqzlodoywgegxrlgbhfabeqssazwqohpspfswzwrogxwuynbnhzoqdgeuhhchzpllunykhigxxyjsznsugipicgvixbmbmgykarrjmyrneecdiuvetefijfwifywnnrjygcdporhyvtsvwdqsxphysuzygvbvhneqtnzemrpufpuuuxzdidxarwygsumncjojvdpxqlealwzjauvzkzanjzxftmwtycrqqkhjnzbugywatreuyxuomicylhmjlkrksvbitmpmqpwrfioppzowzxolhfrtdwuomzgqkjysoigliduimbrwqlutwjqxtoanlhrcozcergzpcfjjmnlzcbderwhasecztksogdrgefnbdavwrwjvnhcugawmjwytkcmbexgheizzofnpbtnfzaapxruauyvpyholysnvszhlwansjvlwnjtmrwbtydobmoryatizkknzotkjzhfafwcceqduccintnvvxxhcvftkcehhzzaphqktshcoviwxyjapyhpuhhwbpbgdpbndawcovibpvadrndxkkbsbbtwiabgdjbfryergymjlgdrfnjpmiqerhqeiqznfxfwepecfuxqcofqzwxsvimqxnxytcjbryqbawrkqkpyhoaupcbxxdorzbypqmjqiumstmhhuwgjyevikelqngzuravlxicqxftgtkqgmnetkxlcqvfpbbaebzqevhaecqsezdjibmzggylswnakwpygidjnkqneufgpcpoppmyyancaupvjbeccvfsqfobmbmopkvamorrnouwqfohagqbndieykfyrpixehkeanueqpmpowkalhzdsrcflqvlbxhtyrxgyzonrqkwtgcanyieasrizbgjahtxjltgesonsinbkkkqlfywzmuuzdwoqzyioifepibhktzzlugttmeluhvwmbrrpfrhtxvjzqpaxrqppxphohexgyrpiswycxfnyofjlzbqifgutdbzjtvweccjoswpmlotvklrknuxviydpjfsjfgxkxmjxmqrclymmzzgtvopynjbqgprmuhfxjyeplhdjmylspcemselcrlfwmtalpddxwufnggmfqzzxqvizangxjbmlbbluxthnsjjyqszoduolyllimvhltwbudqluxhnuttnrmlmjfxyyxboiuzyyaicxfwskwtrmlenfnhhqowqancolgbrfrlpbcjscajfremcxbxkhlhphkoyrhlygwirbzkwllazbgkrrixjjhnftbcouumrlhfyodjysxxtbzvknfzjsjovkzmszasonudnhtumcqalkkrvsdxskvajzqjyqjahvfpxdkfdhdgauattlkrlyzehsjeggvhrcnljrcnmhsofqikaerxejmaqkdrihusjogvdpirzgcnvaahahnaevhhoowoujdzabapbtlpunzjvfvtfchfrxetrihpddwegpdcsinwlrjocplxobltqjqsoiwocoorpladwhyeykkpelkhrjuuusvrtjugruslbctduqjjcopimnrutmfsltthmylgubgccgnmldvtylugtjuktvnosvwiwmsauycbvcyjcheeuxjhmrqwjclgtjapjlycmalbcpixxkoamvsvydxyyoorrypjscsuvlhwkrtmsangkehrvidffynnrivbvnbtlvimxtugggocwoupudafliedfimaficumawhbmlxoowimlqsnlrbfpxkzghneddmqmnxwyusvqptlmgegchqsmsrzwumejlylfdhfgpxnbepvzfpkwayttqxmfxifevmtlkwqmuuxmuottxyhqpdlmfyqixeetkbonulqguespnozeefecbbjqiucpteljdffzaxhbtonritvodqacrslnetudfosoikjfvacmgjlqgossxqhcthycpvglxconcswyxxtfhzkmpauvwwpirdxasydbzxngegqbuofwlnidnmywluzxnwruoniqqorywutltleltltwasysoskrnlzxhtplamvnhiwoyhfmygnoqunlatqxwokmkjbfmmltqkrbyjcxulwufofpgbuiutjvpprvahsdcvhrizvhvrztbazzhpcovhuikkostdlfrubrdfkiwvaadolfvdjeowkmlduqgiynhtfvtgjdirankgndxnmgwirwuuukcerwxriissnyufsynukfjqabrallqmriqkogldqxwcsdtfpkxxjuukeuafukqsmdpigedbwcxbhzbmivqoxpbscbittnuohvyybofhsdjxplphpywqpkjeztqbskdhcpplnhacxnhvqwzadqtncqnrdfvmqkenjpawxdrtdraklpbyxtixvmihcwnzydjxfadibrngcxyhwesslvegvuoliwmejjzmokqfupkatzatwvmffjfianyxevdootqkltdtrgeyhknyoygvkpowdcrtfubamvabweefhatovjsjsdieetgtiyqydfgizgjybxaxrvaxmijdxjllnntytdrsacwyvwlbunftyhgqeiqnclhlyegihpbxapmnbtjbfdbpjngpjolampasktoheeoaefubbtmyvgnrxuncsjpzlykvfydynmpwpomjnutucingqprzzbtyzcfcjljhtxuaquplsysrbhgatffxterucvmeroxijjuyjnxsnoxvmqomqjipwfctlounzagseucuufwczeoxcuckdimjbzkkfeuyhchygqhdbzzpzimutlooiaqpwqipadzktgsuvfwfnidltuwksblqamwuqivdrvxcyjjpvzovyuiaqwqgyduwikqafroyjosanuzfntyeduoplpwhllsndfdviwzmcmjxrokkzidpijclpcsmisagseglrdaxobjziuvydzvwswazfejpspjkpbfstiodratbwrewokiznpexycfgjupggfphwvmhrrychsdzrjrgmbpbpkuwsuvhnfigekhmfqggcelvnigpkonepbrypgthdijavsxtonzpuzrcgjowqwnhpredtsocqeuezossuxsrdxuxebztqetqmyihqtsvcnpovwgtwrxolkfkjeobrgccuqsjnlpbpgjrhnyogixbmuyffhqcbvqovlpqenrwkwontkylvcontkcuwljnjtxvrqundembkrbvadrqtzpcyzpyrcigfxdumphgnwhtqsjgoeyvnrzwqxgztercnnzeiswwufqsiwscdmespjfvvhflzjwiobfwncfniwnitqbojxnnqfdseauxzpmsbsqbdpxhatfidqpbbxjckijeyokneszdbzdfmwvmfgxfdpeiixueqevxvdvrbomappgpkthkifvdoeszckgdjcyofokloqsvkwskvlojtnujvumhhsgkgqeozheqaowddhoibculjgniquluygxareydwchcuedgsyopkdrfcixadizpcumcujwdeohnnilmwatmczgixflzdqaanqtfrwislvypcjitylbikogbuihphnwndtnynxtapjbqrusilvctjutqzwrgiiakplyuhxlzkbvqfwvkszibjqkgwnwenenhipysenbrhedqxtxexfbxgdyieincmrswptiqmbgwjxlpactbnpjrjrngbwrtgjweiaveoijxmdmdjdlrkjhmwhcirrqvrfthiytscjokiugzuggyhvpxetttnlcrffnmbqcshogdczbssgrkchmpukwqychupcpjmbifqppvlmdymysfgmsbttupmklcpehofqtajbuwuouyvaulzzzybcwwvcpnqkoossqxemcstvazilkigbhhytjbtzdiddaseiohckbaoncigcghxqnvclnfvngzrccuutvyoqzglbascmkuuabmumsjuushxxsjllyycndpzhaprrtbmhkxwptjdilmryhopbjeamkiarmbakudclqzwclpjgusakfjuemyohjvaqgutnycriuegzwbulbfdvlkexszqwhewcixeplyvjgbrgnapusbfyrtzifmlhxpwarprfzvgiwmwhprxubqwmwwvtjqnpjxkkxxaaizxshoemvcmqpyliislpaqelamelcypijuzcwsbmuzfmyoligcftoaxlhsecctckkvwnlighaqjjxphozxyrmixvfdeztznxvdrywrbqtmxlmaodfnqbklzdmkxjfofvvwlyrkbagpydrecipgjxcmnmdactgqpyiwgocwaxhxhavbhlkehheoihtcmmbgxkkjtbmavkmpwexmwmchmnugkbicanefuhmythpcrbxwuulvwcqbukdijxsthdbygneqqlrxtduxdpncakhaqbogmpqalctljvejbiuztfenchvjpnicsesotbuzoskbajzrdzodtvhzavcatboygcedtfkslumtkgwyyplbxmdzslktbontistrlemgwltlvmfuapeqycovqrgzdxwksmyrpeelmhdwqjlqvhafwopeguvhszlbbjyitflhfpeposbpdedqjtymbzxwpupeguehcqjsmdrwxjavcttemlaitjknaddirybinyxcvyhpzfpzdxvyqtywchitnzrcfnjpjczivsphxsbjnrexrpgolwysqmycynxlpnwjdrqzmsoitfjzskytccacjgdvvlkmvvtywwsfispxiujwxwvkmezylbzezohmyzuaeubkeeslahgktieqzrhykuvfcbrrpokvkcjupalfibwwgzlpmixwjsjjpirehkrymecowxbmthkaiuflvmlwcqsyovnotnqglijatfphszqlycvyxphhiytyutepmvegdvmwdiwodvvkqpylvywbqpudnaovspzmlfjfkqchkghnzgtdladodlcjdakvobusksoraoyffodpoipntvsmjhmwjhynvvexpqrvjapyaehmvzqpautdghqvpzpbfrxzgqqahedsbhvpyrzjxmjcneuduxpagzlomjrscmtvzngyuzjaeceftqvjqzpymqkkiguzhuiffjlqgjxlviffjufhexndttquaevphuuypsyslvnvjeknjrynqqonxrijswfzvfdfflbafqnrlmtbcotzilvdysutopdshqskjnlrewkbgrhmidqxcxtesxsnmouplvguhmhomdktvspipsgkxtvzwokqjqffpxocezoqmlsynrmwxgwvhcftudjmyvkvjgchjkzrjmxyalvkmphpsdtssufenyfgpozcwhlqkkugnhvmgrcvankdyglscpmwoubxgfhlzacfkjqhfjwkxqufhgtalenyfuxsyzaruhxmdbopimbvavkyvpcslrnuwrvsmenmklzklxcpevvdybipqltixhfafbskxugkcvujgvqhwilajwllerctxtutdrjyzfygtenoifrmmrxebfmutqtiqwfhxrnuavwhunuarvzuooflqboghxukyqenxwxibpacbtwnhedifyxnkhsohgktqfnftzpebpjpawkijzevzdhzdzhvefoziyumtgiuddbxbfyxsimjreethdokpqdbaeblsvsnwxisflugvhmptlszgewapaixxggtnnqxkhsssxatvnsisrvxcpzaqequcfoxfgavagcfwdzpytntvetmbvloulliwdowatffgaodapbpmztcewmpfjrultckhhuwsiyuqhjslnzagdbszeeiwkbvmpbbmfktscrfudplnywrtkrkzbxsobjsnewcvzozmytakcqtebutobfxadtxlrrtxrumftcwrvnmuxflookljkmyotbeztiivnwflkucnhbegnbplvwtqaagxebmfujrovaybppirqrcqcobhcmjlmhrnoxbdmbhdkgcltxcmtcztnyityaamkchrxcgqnjyidqeerhxjkvlzrbmtltxxnavjtrgelejsbtdnmrhaslpqkloeqdpgmyakhqvnqugdcttgbhpazhjlsqquiibfiejparblmosezhtxhdyklnzjsjpdvmlbazsogcgeorsflnwbhnjyyyzwrrdtdzrzgyajgxhwfwwcvqazowwqerkbxgvpgthsmiyyvmyhhocgqgzkldnzpacazfhqfruagnkkdlvuzvzqebbsmlfcmgrssmvugaxnhbwlsfwzwnydhwtbzpspjavuebttbhyzzudjtsmfeqwhtsxekijlqfzrozxpepzgpbalanxxxftbhmsihlrdzrzgmbcwmqmzsrkisnimrxzzmmyevetmjvgaotsdwekpzynvhzcrogodralrkdbxlrcnaqlcvosyjfurepspuazlgokmxleucexobkallosnfqgdgpjoarztvodglxqkltoonsgfekkrulpzqobewpkiyadpkdhpaqaxggprtjuczsdkisavdtqqexkagcktywratoywvpawdhdlrrmjberyfognnxsrgauuqdnfpsfjoydveuwqdxouxywidvrsiobzpxnlxyijizjmytmfdnnwzyhivacaqcxieyqhwuubnecdgjjujvjfeflmjrsaaeqkeefuwlugxqrnqpqqbbodangsrirypfmzwshscogfiqegbqtlghyoqiwkxyzuwmajqqiwmrztitpzvxtrjmhpebaxknzqvtypyesyzkvjhfwahdzisavyhxwdipkhjshwgvroxadkdqhcmdaehhfubrlpvuiqeehopkebcbnxbgpsjrkftlojewyeyszqpovvunvmdzqezffmnmuciyfxlfymvjgzmkqdblhbmyfcngnodiydveftppyqukyeluimrzlrhtjaalspcotksnfyxshbkzdfqlzymlllypyewboohkmrjbpyknpzviydsnotwkizjddpugwhgjfifjupsvtvvgposoqpnhkautygsvxpnktdlpcqftulcpaxbkapuisjrrlhsppxscneibxhbcyfosbuawteqxhxodjylxvmzjliazawttzahguvextvhjqgwyuwulfykngnnihqiadfccdbcynjpgtbnhhxjdazmbqtpcyeutprpxoptakiodpadmugynnfvmmbmzdgqtqlabosgwnxvbdppjdiqllxazoicrknenrekprijxfeeaefkxyxaebqacqhueosjnwnexmutheyrbklysejnngszsdklffsomcxcelljljjtfbqqnrjdqhjqutgbwiyemsewrydqybmgjdqkrzbjcsnkbfyhpfcpqetuzqqyngwtthahwniuwvotrrlibzoluvifkxykowsyetgtyxoztfdjoxnlfgrtbtgnwllgfkzspvbtoztwhosyefumlpuxvlhtckqiqfxfmeovvieiqlybznufewyiwdwaegkfotsldzezvyoyxaflhnurrlclbtucdcrcxvksrlmxyqihuxjaqgjzjkmamztlayhjygwkhykzmpoyrrzwrnygnljgeonkcksuwyxwmucozccatayzbbyveanbizbukajlvhxpgtrpxfzmathnykunbmacwnzoqwnhehsimsgvtrxudflayuwihnpedwxltdybljklcwenanzdkiejztazwkvzfskbbglfszdlrqflydteraagdxgbatbocynohllrvetumkodkcksenpxxuhzbvxveskxrcxkuobcpfeizbdevxnobxmimcnxqgvlqxkcyjlaxracoefrgjdzeliohafmmowlgklrdgbgemojynfjuoffptoojxxktielabmnlxoadpcjwsnefinkbsmyooitlbtdgvbvigmnfailkzoqktujptinmtztxcimdzkghwnxgajxezvuzgefsstjlqtwlxiztjqmqedhcotqgtnefalrvypzgyfvedxnlkwdnwoonqsogvtgglprfnkpftlpknxeffguyfaluphbasxohyqruqwepwbfisnzlduwsuyhhbzgsrakwtynjwyeczphvriudsyuxkyuhvprwrsocztxejxrhzxxmvmnjlplxdrulurujnazmhglzpfsljleudxotvtgqyrdsrvngfxvlukrmfgpvrtrmllpbdrmxukwuxcfuthdcjaikccpiugzdiuvqqzlswjlgflpdnwvjgkirlvyzomxhqpfwcuzqyodpqzjgrxwyftnncsedxycynvfhnaiehiaciukprvcqlxdttksjvzicllidoykvbasabfrbegypzquyljxgkjcobyuccwlemszdlasookqwlowxhxuqtyjwrejfxfoihvqescixbvayvlmjwhvypopdvsivudyigfyxkiwlpvhazxzlanawmplphbvtgmcmeuncpywmdebbhohzqjlkaexfzntvtjmqgxncmlhduydsslvnsloehgeuawsygjpiqpiygurhejxpvpuikgtkcdpvcxwwdcxmbdzjjjeppqphvmpombnrfbbrcuffdjfxzbgkizajwgwbgvisxlwerbjvnzlnjkhckkggdrdqltctmbyosqasjzabnmpvmpgthqodmsqapenwqwewpfofexsedrerggudmjoljiqsrtllbaawnxofrgvwvcsjlamrceriogyaxwdrgguhlaicmsxwnenqjkohhrxavuvgugwjndoevzcavrhdaxjkavovxhdrmwtdzeizxhiowmubyaqbfdxtrjjafhyuwouocgohnbhfrtvxplrszwmgrzacuxajzuytinoqubgdwmfcmyyukqvlmwzdnwoscillbevaumdwyqjdcjgngyjbcctsbjebxzugqrmaexfemkbdsjpsfkbuwpyiglrsizxfmkbppzbsrfcyvbghbyubhnstfssevkcpwbgzosflvcepbvohuyhwmnzzneeqcwfibrxhaekvuhoibhlhrnjefbqdvodqrgsklxnezxmwrvztbsuwougmwplvbbfkplpmwibsoyldjeqehornyzmqcepkgtxugrjnollpppaezmwcsubftyycdviyujjawlwysjrfsideqfrvqbrvuczgoljwidlccxgundkbpardbyupvufamjmfyaslrzpzdkqklcnmlyhfxdxyslbkwdqsrxjtretxfljathufatmxhjotvakukdvmbfugkuomqeuejevhlzcmnuhonfdcmhckogoggzohhfveqjueckxmuoetdpyyxijlvlexekthxjvqsuqcpivmvghvlnsejrerflpcjbobwtwdqdxfzaexqcjvednemsftdxqzbvjfbgzbumnhzyeweszwqumrrhypoqcfbjqzpinqmwdukrjuiqzvunaevomdafkdshzavmgggqpcsvjzuzbnvangipmeufuwkuvwzldpqdjbvispivshojmnxovkapzpalmsiatnkhhjodujepbalzdotulkbigogavcecgyseqtxlijetgvskrhjfdqfnppmsuumokklsbzcmciqtahfjryzimbbbjzchspldwxxrygistfrmspfkdpzvjfmesqwwhnumhhhkcutxnlgaccsucbmrkyznmkynvdwpoxljhlxjxmdqqrfkkbsooinutifwfefpvrwcdgdekmrnklctjptegczwfzambfzncdxildymxjajtcpkxbfzlemwakzojzyrtkxesowccstqpciyixuslbblhpowgikhqpoygmzukfmfjicwplpvqozonpquqdoacponasanlhxnlejsrqrffgpvgitrfprkdwvqtjaftiiedaopwmrvssvcwfwutzxiskmruxvdnwlqtueahuayzhfbledvmqsrvbipbtovwqllqqvnioyhfjnsnhgffspwaeufbxsczktvpfylrhnzuxrvfiohynkhpiashaydyoafvlbdfbtohvlywaxabomzdvdckiyjbsvxnzaevkdeliyjgvmouqrjimgifjyhnbdjhdauycfkkbygthweomgmntqraesbosgbiyexnajlzbylgraiuccdimfndnqccokqihaguxyqmqkgjaeigmxllrzdrjgtwywcacvacegubregybihzkjwvfpxtlycnbapaftgvhbwkockgheasvbhlrnvzshrubqbampdzzhopovhsglijjliqffhquefmlmnubfexclvpeoezafwzxmbghycyfwfnueymyhruoacdrdtpowijocdkjarqfxpauydzfapwqyoanjjhbxbjnzqbcevnzmetsctiauwrroofnpgyqknvlvprbluoaoftrizbnpxtmjanqjuwbkwzhokybefyxrncwwpmshhtrqarxmoswoagdsepwjkfwxayhpksvpduzoioqlzwnbfuwslqfrarcrpuiwlkjaijzmfyxqiwuaihptcnzrjbzyvmrxcpvbontyluzbkmztvtzwegmgbwotzgrtjpjeivbssodndsoipugrlkqopylokbcvcxdoehnigwnbhyrytxfjdfcobuugyeqqbsdxmfeqrkinezgkvcvtjlhcmkmbalizupuxgyqyngpmqknwjhienhdlgoasbhgasvdrurxvcmsbepgmgmojxytqsubbisxbqrmhhnljgoofhqhfoxwnsiwhtfmpwbvplsvbdwwhxztwadwobbochyagkpudrlimeakajhulhbeyikgkullcpyldhegdnqajqfmesuwdjpxmpzixfodiortjypugiluvhnmukexrovxtkrpzajvmbamxmgvkmcborfbxyxbxqukxdwzphxscahxncirocezdkkrmnbzcvomkkietmsuyzfiorqgnhhpsftdityldqfeudxyeiufttkizpclrsynselmwrvaicfxndjldznockrghaugbcrjmojnxascrxuqrnbpiqgktjgfqwisqpkgsctoyauaxdnrwhkuksgktjvmjdnmszzpoadbfyglnhdudcpsdzlvamtpspwctbnnhegmuqbfuiyyecukfoiyfmftojsrddqerrzwdguxdzxbpicpovmuyqcymgvjqxvdogliihcdungqxhmrhcrmymgwxzwaqorpltroedtdiifzlaozxhbkdfasfuigctaeucxtvruamuefthpcegvnwszfrtatcvolgcldhnqpvnnevonlliyymbxxpbwvgthrbhoivubqucpjihzaicijjpftagaphuekrwkevotwyxccalwhajleheyayceevitrvxejnsdmsfgdixffhjkqfgjvzcaejihpdogndakhmmqxzopwhlmmcwsxeatkvxwrmsmebjtcmmgbbeiwextsoxnacmjxzxrolhraudjxvkghlxhiluejxycqxtbmictbclbrcndeentkhnfsrvuaxbilytojmcfkajmffqkonvzncqsfxgfjvdtlizdzlqbmxyqbueakllblotswgpdjsukzumplstwcwshzloidjcxdlnggljoiosccjtmvezviclkqvyoevbsehsbnvtbisqhwpapmzfmmipftzxekdacjixmfytoqtqrsvyanqegkxjwgqpoocmktjtdjgbxkyjelyqriikqvcippzbblmcgdzsjimamhytqymphiuihjlocpzzhikfmdmjshzlslycfjiifttfkvgjrqpuzonmqmyisrebhsoqaaaszhqsmtnvafblszlmvdyozdmxsvcpoupczdkoqfnlehyvmxxidneeavxhkzbbfeopumgjbwzrqjmwlhgxldbtzzxlhocemuuzxbjnetrobzysmeipddhwyckpibdaqbizqlssyuvemxmfiydudqsxgqcrbcnpkreayzhstnapubvfkhfsawzcavplwdmzirlardsxsufcexdqczgrcnaiwjvqnvlqbuqwlyecmvpwcwvxsiorzmvinsukqvbgutsgctrdzleqkcpysggqhovvxmvkrdtnuvbdpizndlesvospgavyjwfiqsrewrpnrngtvwetewjafcqjohgywlfqdiydeyuhtgccgnavkitkaxerhoxmnvptgtmunpizelohhvaoczcnsnqjvarcmefmclyrralzyhrqbwueglugvszhnizjwatrtfgvcxrunvkpnvccthqbrmonnqrsxlxsmumefrorncahfgtadvoumtjngpltzvjeykuapzebrrrtadbxvoujcxrxgefrmzqmutbcgruzfpfpxkxsyphvbtfrkcvgvbqgomtzkwmanqszqsutcioeeffwumhsjgksizuioxhnewomriiyjnmyzmcmodsgzhlxchcksgcgysftbbgawieltycqvfzuvfggjwthfyuawccripxzrwiamleyvordfwwvprobngtgjugfbasjkplufuqcaaoypzqbwmrpmbpuuwbcsnlvkuwhewrbprjhdzbdbyhetlhrjhucwlxkblsgfkurnjvwlnmpakonqgxytuuuwnulujyodsvyzbpsojxyzqyxcegdwrcawuidjhpcohuqjhdfciqeqjcsohnhmcswgmhlzaruehonmlmawsthwqdpctolezxuogpkjgezjimeotiwtheqssfdvfmwfpxyundcrpxxvetycmguujknrjwoiwhnkdjuzkegxwkuitpmcparanlkeefgitthvwoahuwknazrbkrwyvcviduufyaocjeluifhmmilyxzivjicxwehjepvtoqxmpehykkjaunbyagptegbpxajlwbkvzqkpyhwcvsyrficrrybvaypjyttybkpumatdvdgzrzfrlbgahdlsilckhnyqmldmdtvowjcspjbichkzswwlrjzcrwdiactwognblspsbzmqajrcvtfgqbwwpaaxaaxkcoplxlavxkrnhdygdrovwhhtovrsjqxciphirhppqybbzkqsnkfoqmcsbylbxuahhozgldkdhlrysvazwyoyqklqzhvwlmrjdyxymejfoozpxfenblnvlqxpnnfhjtswfikkweuywiatwfkbseesfuybdqyewmvqlidwfkhytqftwzpewqijyfvpobhdjfsopnqsuagyxqkwlfywatdjqskukaxkgqwtrmpzjejqzkbdhglbdtkuesppyjhppliftkimjzlzrlluadsfepftkraizlduebhrlnignytpwumldrjvrodpyizltromvqktokgtohieespsyftglybjihqhmrgydgdcmvroeiloygrbczdxiebrkfmzjekyextadstsihotfxgiaswkzbmdfvsdietvngxhfgvessdzmnibcrirlpuiuibvbvhworqhhnobyqywuavpotlzkkibhhicsdaibjxjfbhvmyixruzjaknielvcrnpowuvcarsxfqpveyyaubdlmebiqqcazlvoefohjnfxaamxbdftbdvqcnzjmukergzfypruqhbrqlhkneheshhvgmcxrzkstjhldbjkqzozmtwlyjsieuglkzkozcvmfcdrpuzdiwnhzwapvswnnlunjtavzqjpuigmxyuoroixaguqnghayvxyafnlnfqmmaozzxfudhwiakpbtnmluqfsloufegqkyjdoidngowzigmatgemrhqzahdhscommhgeupcpjyywyaqzhjqtsceuldtklfuiiqdefrhtfogadahuawfpcfuosvrcglwibzpxmphsrzeudztbgughcqsfieiczvlamklmtmonuhmhofsovmvrevnuvtalfgsdbekopvmapxhmyhoqohrcaqjervkoqhwmugqocfypnigfodorsjulbzkincgyvydcbvgjhxmigmxommftbabbsptjjvxzxsjxearjeraoxigxweuglyxhjijhysrvrqutxokcnjoqokpkpmggfsaeumkvzjmflepcsoxxylwzdkazakjmwelnjsmghfuflhkmjfcglnpcuasnewwfjmgdvxpgzjrsxnptzelqluatflhgablqfcsfzfozqshzhxfumkcglztaedmwwlosiysgkrazisfdugyffylqdtssggxmhttlimywbelgdodnphwtqmnreycolgncixomlxmblbfbgnzcbxvhyiasibcbugcpreaupuhzzrnxwnhzkprpogncoxbupkmsusmwzjgafffjzfjaibhxkwwetntupobdoyzznabuijvpnxyfyrzbjgqjltziybzislbrvvixxbfjutbfcksrqxvnbwakwqnuvjtnjggtngaeihiegcdbuscdmozrjjpncuqnarskptirqqqejewuvdfexbugqkybhvndoiixuecyadqeaamcduapmizkoikcbwhlqurfxgbnfsrjcpbgkeambgzvqjihpilkpbibewllxplvrfqejektqqwlxdbrmikgpeebiftbnsrcogmjbbglkjtimibcrhsrdfienrlubgjkhxsvvvdjkwwrpxnhlsnqtihkxazdnnyymekdxxnsnjdsjesjmvvpftitz")
assert 4 == solution.partitionString(s="abacaba")
assert 6 == solution.partitionString(s="ssssss")
